name: Blog build and publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6.1"
    - uses: actions/checkout@v3
    - name: Build
      run: cd static-site-generator && swift build -v
    - name: Run
      run: cd static-site-generator && swift run -v
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: build
