name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.0'
    - uses: actions/checkout@v3
    - name: Build
      run: cd static-site-generator && swift build -v
    - name: Run
      run: cd static-site-generator && swift run -v
